/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_math_CBLAS */

#ifndef _Included_com_utils_math_CBLAS
#define _Included_com_utils_math_CBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_math_CBLAS
 * Method:    dgemm
 * Signature: (IIIIIID[DI[DID[DI)V
 */
JNIEXPORT void JNICALL Java_com_utils_math_CBLAS_dgemm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
