/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_math_CBLAS_TRANSPOSE */

#ifndef _Included_com_utils_math_CBLAS_TRANSPOSE
#define _Included_com_utils_math_CBLAS_TRANSPOSE
#ifdef __cplusplus
extern "C" {
#endif
#undef com_utils_math_CBLAS_TRANSPOSE_NoTrans
#define com_utils_math_CBLAS_TRANSPOSE_NoTrans 111L
#undef com_utils_math_CBLAS_TRANSPOSE_Trans
#define com_utils_math_CBLAS_TRANSPOSE_Trans 112L
#undef com_utils_math_CBLAS_TRANSPOSE_ConjTrans
#define com_utils_math_CBLAS_TRANSPOSE_ConjTrans 113L
#ifdef __cplusplus
}
#endif
#endif
