/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_math_CBLAS_ORDER */

#ifndef _Included_com_utils_math_CBLAS_ORDER
#define _Included_com_utils_math_CBLAS_ORDER
#ifdef __cplusplus
extern "C" {
#endif
#undef com_utils_math_CBLAS_ORDER_RowMajor
#define com_utils_math_CBLAS_ORDER_RowMajor 101L
#undef com_utils_math_CBLAS_ORDER_ColMajor
#define com_utils_math_CBLAS_ORDER_ColMajor 102L
#ifdef __cplusplus
}
#endif
#endif
